# Generated by Django 5.0 on 2023-12-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_district'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
