# Generated by Django 5.0 on 2023-12-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stationmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=20)),
                ('master_contact', models.CharField(max_length=20)),
                ('master_email', models.EmailField(max_length=254)),
                ('master_gender', models.CharField(max_length=20)),
                ('master_address', models.TextField()),
                ('master_photo', models.FileField(upload_to='UserDocs/')),
                ('master_proof', models.FileField(upload_to='UserDocs/')),
                ('master_password', models.CharField(max_length=20)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
