# Generated by Django 5.0 on 2024-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tickettype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=10)),
                ('ticket_type_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
