# Generated by Django 5.0 on 2024-01-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_tickettype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_name', models.CharField(max_length=10)),
                ('boat_capacity', models.IntegerField()),
                ('boat_entrydate', models.DateField(max_length=10)),
            ],
        ),
    ]
