# Generated by Django 5.0 on 2024-01-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_boat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stationmaster',
        ),
    ]
