# Generated by Django 5.0 on 2024-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_tbl_stationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stationmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=20)),
                ('master_contact', models.CharField(max_length=20)),
                ('master_email', models.EmailField(max_length=254)),
                ('master_gender', models.CharField(max_length=20)),
                ('master_address', models.TextField()),
                ('master_photo', models.FileField(upload_to='UserDocs/')),
                ('master_proof', models.FileField(upload_to='UserDocs/')),
                ('master_password', models.CharField(max_length=20)),
            ],
        ),
    ]
