# Generated by Django 5.0 on 2024-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_addevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='FoodDocs/')),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
