# Generated by Django 5.0 on 2024-01-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_food',
        ),
    ]
