# Generated by Django 5.0 on 2024-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_delete_tbl_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_description', models.CharField(max_length=60)),
                ('food_image', models.FileField(upload_to='FoodDocs/')),
                ('food_rate', models.IntegerField()),
            ],
        ),
    ]
