# Generated by Django 5.0 on 2024-01-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
