# Generated by Django 5.0.6 on 2024-08-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_boat',
            name='boat_entrydate',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='tbl_addevent',
        ),
    ]
