# Generated by Django 5.0 on 2024-01-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationMaster', '0002_tbl_assignboat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignboat',
        ),
    ]
