# Generated by Django 5.0 on 2024-01-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_stationmaster'),
        ('StationMaster', '0003_delete_tbl_assignboat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignboat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('arrivaltime', models.TimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_boat')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationMaster.tbl_service')),
            ],
        ),
    ]
