# Generated by Django 5.1.6 on 2025-03-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StationMaster', '0005_delete_tbl_assignboat_delete_tbl_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
