# Generated by Django 5.1.6 on 2025-03-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_addevent'),
        ('StationMaster', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignboat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('arrivaltime', models.TimeField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_boat')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationMaster.tbl_service')),
            ],
        ),
    ]
