# Generated by Django 5.0 on 2024-01-24 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0018_tbl_stock'),
        ('Guest', '0003_initial'),
        ('User', '0004_delete_tbl_ticketbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ticketbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Passenger_count', models.CharField(max_length=10)),
                ('book_amount', models.CharField(max_length=10)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_tickettype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
