# Generated by Django 5.0 on 2024-03-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ticketbooking',
        ),
    ]
