# Generated by Django 5.0 on 2024-03-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationMaster', '0004_tbl_assignboat'),
        ('User', '0014_tbl_ticketbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_ticketbooking',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StationMaster.tbl_assignboat'),
        ),
    ]
