# Generated by Django 5.0.3 on 2024-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_tbl_ticketbooking_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ticketbooking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
