# Generated by Django 5.0.6 on 2024-08-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
        ('StationMaster', '0004_tbl_assignboat'),
        ('User', '0016_tbl_ticketbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_eventbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Passenger_count', models.CharField(max_length=10)),
                ('tickettype', models.CharField(max_length=10)),
                ('book_amount', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=80)),
                ('status', models.IntegerField(default=0)),
                ('assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StationMaster.tbl_assignboat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
