# Generated by Django 5.1.6 on 2025-03-24 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_ticketbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ticketbooking',
        ),
    ]
