# Generated by Django 5.1.6 on 2025-03-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_ticketbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ticketbooking',
            name='assign',
        ),
        migrations.RemoveField(
            model_name='tbl_ticketbooking',
            name='service_from',
        ),
        migrations.RemoveField(
            model_name='tbl_ticketbooking',
            name='service_to',
        ),
        migrations.RemoveField(
            model_name='tbl_ticketbooking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='tbl_ticketbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_eventbooking',
        ),
        migrations.DeleteModel(
            name='tbl_ticketbooking',
        ),
    ]
