# Generated by Django 5.1.6 on 2025-03-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_eventbooking_tbl_ticketbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ticketbooking',
        ),
    ]
