# Generated by Django 5.0.6 on 2024-08-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
